import '../globals.css'

export const metadata = {
  title: "My Movie Blog",
  description: "Generated by create next + sanity app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}


